### ISSUE TITLE
non-relative imports should resolve to node_modules

### ISSUE THREAD

**Issue by nthtran** [css-modules/css-modules-require-hook#14]
An example:

```css
.root {
  composes: box from 'css-utils.css';
}
```

Currently something like this is scoped locally, i.e. `./css-utils.css`. Shouldn't it resolve to `node_modules/css-utils.css` instead?
