### ISSUE TITLE
Support to resolve index.css

### ISSUE THREAD

**Issue by lucasmotta** [css-modules/css-modules-require-hook#83]
Hey there,

I've been using this library for a while now and it has been working very well.
But I started on a new project, where they organise some of their CSS on folders, like this:
```
/style/typography/index.css
/style/typography/medium.css
/style/typography/large.css
```

So we can compose like:
```css
.item {
  /* webpack can resolve the index.css for you */
  composes: size-sm bold from 'style/typography';
  
  /* or you can compose the file directly */
  composes: size-md from 'style/typography/medium';
}
```

That works fine on webpack, but this hook does not try to resolve `index.css` files if the given path is a folder. Is it possible to add such feature? I could try to submit a PR to include this.

Let me know!
